version: "3.9"

services:
  auth-blue:
    image: ${AUTH_APP}:${TAG}
    container_name: auth-blue
    restart: always
    ports:
      - 9001:9000
    env_file:
      - .env

  resource-blue:
    image: ${RESOURCE_APP}:${TAG}
    container_name: resource-blue
    restart: always
    ports:
      - 8081:8080
    env_file:
      - .env

  auth-green:
    image: ${AUTH_APP}:${TAG}
    container_name: auth-green
    restart: always
    ports:
      - 9002:9000
    env_file:
      - .env

  resource-green:
    image: ${RESOURCE_APP}:${TAG}
    container_name: resource-green
    restart: always
    ports:
      - 8082:8080
    env_file:
      - .env
